name: tests

on:
  push: &repo_trigger
    branches:
      - main
    paths:
      - .github/workflows/tests.yml
      - pyproject.toml
      - uv.lock
      - '*/**.py'
  pull_request: *repo_trigger

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          prune-cache: false

      - name: Cache HF Hub
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface/hub/
          key: ${{ runner.os }}-hf-cache

      - name: Run tests
        run: |
          if [ -d ~/.cache/huggingface/hub/models--Snowflake--snowflake-arctic-embed-l-v2.0 ]; then
              export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1
          fi
          uv sync --extra dev --extra test --frozen --no-install-project
          uv run ruff check .
          uv run pytest -vvv --cov --cov-report=xml --cov-report=term

